services:
  server:
    build:
      dockerfile: server.Dockerfile
      context: .
      target: run
    tty: true
    stdin_open: true

  client:
    build:
      dockerfile: client.Dockerfile
      context: .
      target: run
    tty: true
    stdin_open: true

