version: '3'
services:
  server:
    build:
      dockerfile: server.Dockerfile
      context: .
      target: run
    tty: true
    stdin_open: true
    ports:
      - "4390:4390"  # Expose server port for the client to connect
    networks:
      - chat-network

  client:
    build:
      dockerfile: client.Dockerfile
      context: .
      target: run
    tty: true
    stdin_open: true
    networks:
      - chat-network
    depends_on:
      - server  # Ensure the server starts before the client

networks:
  chat-network:
    driver: bridge
